# Generated by Django 6.0.2 on 2026-02-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='vehicle_model',
            new_name='car_model',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='car_brand',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('EV', 'EV')], default='Patrol', max_length=20),
            preserve_default=False,
        ),
    ]
